apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxrisk-portal
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taxrisk-portal
  template:
    metadata:
      labels:
        app: taxrisk-portal
    spec:
      containers:
      - name: taxrisk-portal
        image: mmregistry.mmvietnam.com:5000/taxrisk-portal:latest
        ports:
        - containerPort: 4030
      imagePullSecrets:
      - name: mmregistry-secret
