apiVersion: v1
kind: Service
metadata:
  name: taxrisk-portal-service
  namespace: taxrisk-portal  # namespace the same deployement
spec:
  selector:
    app: taxrisk-portal-app  #  Pod choose Deployment label
  ports:
    - protocol: TCP
      port: 4030           # Port extenal
      targetPort: 4030    # Port in container
  type: LoadBalancer     # LoadBalancer provide IP address
