apiVersion: v1
kind: Service
metadata:
  name: taxrisk-portal
  namespace: default  # namespace the same deployement
spec:
  selector:
    app: taxrisk-portal  #  Pod choose Deployment label
  ports:
    - protocol: TCP
      port: 4030           # Port extenal
      targetPort: 4030    # Port in container
  type: LoadBalancer     # LoadBalancer provide IP address
